// src/views/LoginView.vue
<template>
  <div class="login-container">
    <h1 class="app-logo"><router-link to="/" class="logo">🎯 데이트코스</router-link></h1>
    <div class="login-box">
      <h2>로그인</h2>
      
      <MessageAlert v-if="errorMessage" :message="errorMessage" type="error" />

      <form @submit.prevent="handleLogin" class="login-form">
        <FormInput
          id="username"
          v-model="form.username"
          type="text"
          label="아이디"
          placeholder="아이디를 입력하세요"
          required
        />

        <FormInput
          id="password"
          v-model="form.password"
          type="password"
          label="비밀번호"
          placeholder="비밀번호를 입력하세요"
          required
        />

        <button type="submit" class="login-btn">로그인</button>
      </form>

      <div class="login-footer">
        <p>아직 계정이 없으신가요? <router-link to="/register">회원가입</router-link></p>
      </div>
    </div>
  </div>
</template>

<script>
import { useAuthStore } from '../stores/auth'
import FormInput from '../components/FormInput.vue'
import MessageAlert from '../components/MessageAlert.vue'

export default {
  name: 'LoginView',
  components: {
    FormInput,
    MessageAlert
  },
  data() {
    return {
      form: {
        username: '',
        password: ''
      },
      errorMessage: ''
    }
  },
  methods: {
    async handleLogin() {
      this.errorMessage = '';
      if (!this.form.username || !this.form.password) {
        this.errorMessage = '아이디와 비밀번호를 입력해주세요.';
        return;
      }

      try {
        const res = await fetch('/v1/auth/login', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            loginId: this.form.username,
            password: this.form.password
          })
        });

        const data = await res.json();

        if (data && data.result === 'SUCCESS') {
          const auth = useAuthStore()
          auth.setLogin(data.data)
          this.errorMessage = '';
          this.$router.push('/home-auth');
        } else if (data && data.result === 'FAIL') {
          const msg = data.error && data.error.message ? data.error.message : '로그인에 실패했습니다.';
          this.errorMessage = msg;
        } else {
          this.errorMessage = '서버 응답을 처리할 수 없습니다.';
        }
      } catch (err) {
        console.error('로그인 오류', err);
        this.errorMessage = '서버 연결에 실패했습니다.';
      }
    }
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  position: relative;
}

.app-logo {
  position: absolute;
  top: 2rem;
  left: 2rem;
  margin: 0;
}

.logo {
  color: white;
  text-decoration: none;
  font-size: 1.5rem;
  font-weight: bold;
  transition: opacity 0.3s ease;
}

.logo:hover {
  opacity: 0.8;}

.login-box {
  background: white;
  border-radius: 10px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
  padding: 3rem;
  width: 100%;
  max-width: 400px;
}

.login-title {
  text-align: center;
  font-size: 2rem;
  margin-bottom: 0.5rem;
  color: #667eea;
}

.login-box h2 {
  text-align: center;
  font-size: 1.8rem;
  color: #333;
  margin-bottom: 2rem;
  font-weight: 600;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.login-btn {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 1rem;
  border: none;
  border-radius: 5px;
  font-size: 1.1rem;
  font-weight: 600;
  cursor: pointer;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  margin-top: 1rem;
}

.login-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
}

.login-btn:active {
  transform: translateY(0);
}

.login-footer {
  text-align: center;
  margin-top: 2rem;
  color: #666;
  font-size: 0.95rem;
}

.login-footer a {
  color: #667eea;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.3s ease;
}

.login-footer a:hover {
  color: #764ba2;
}

@media (max-width: 480px) {
  .login-box {
    padding: 2rem;
  }

  .login-box h2 {
    font-size: 1.5rem;
  }
}
</style>

// src/views/LoginView.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import useAuthStore from '../stores/authStore';
import FormInput from '../components/FormInput';
import MessageAlert from '../components/MessageAlert';
import axios from '../api/axios';

const LoginView = () => {
    const [form, setForm] = useState({
        username: '',
        password: ''
    });
    const [errorMessage, setErrorMessage] = useState('');
    const [loading, setLoading] = useState(false);

    const { setLogin } = useAuthStore();
    const navigate = useNavigate();

    const handleInputChange = (field, value) => {
        setForm(prev => ({
            ...prev,
            [field]: value
        }));
    };

    const handleLogin = async (e) => {
        e.preventDefault();
        setErrorMessage('');

        if (!form.username || !form.password) {
            setErrorMessage('아이디와 비밀번호를 입력해주세요.');
            return;
        }

        setLoading(true);

        try {
            const res = await axios.post('/v1/auth/login', {
                loginId: form.username,
                password: form.password
            });

            const data = res.data;

            if (data && data.result === 'SUCCESS') {
                setLogin(data.data.username);
                navigate('/home-auth');
            } else if (data && data.result === 'FAIL') {
                const msg = data.error && data.error.message ? data.error.message : '로그인에 실패했습니다.';
                setErrorMessage(msg);
            } else {
                setErrorMessage('서버 응답을 처리할 수 없습니다.');
            }
        } catch (err) {
            console.error('로그인 오류', err);
            if (err.response && err.response.data && err.response.data.error) {
                setErrorMessage(err.response.data.error.message || '로그인에 실패했습니다.');
            } else {
                setErrorMessage('서버 연결에 실패했습니다.');
            }
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen flex justify-center items-center p-8 bg-[#fdfbfb] bg-[radial-gradient(circle_at_top_left,#fee_0%,transparent_40%),radial-gradient(circle_at_bottom_right,#eef_0%,transparent_40%)]">
            <h1 className="absolute top-8 left-8 m-0 z-10">
                <Link to="/" className="text-[1.8rem] font-extrabold bg-gradient-to-br from-[#ff758c] to-[#ff7eb3] bg-clip-text text-transparent">
                    🎯 데이트코스
                </Link>
            </h1>
            <div className="bg-white rounded-3xl shadow-lg p-12 w-full max-w-[420px] relative overflow-hidden border border-white/80 before:content-[''] before:absolute before:top-0 before:left-0 before:w-full before:h-[6px] before:bg-gradient-to-br before:from-[#ff758c] before:to-[#ff7eb3] md:p-6">
                <h2 className="text-center text-[2rem] text-[#333] mb-10 font-extrabold">
                    로그인
                </h2>

                <MessageAlert message={errorMessage} type="error" />

                <form onSubmit={handleLogin} className="flex flex-col gap-6">
                    <FormInput
                        id="username"
                        value={form.username}
                        onChange={(val) => handleInputChange('username', val)}
                        type="text"
                        label="아이디"
                        placeholder="아이디를 입력하세요"
                        required
                    />

                    <FormInput
                        id="password"
                        value={form.password}
                        onChange={(val) => handleInputChange('password', val)}
                        type="password"
                        label="비밀번호"
                        placeholder="비밀번호를 입력하세요"
                        required
                    />

                    <button
                        type="submit"
                        className="bg-gradient-to-br from-[#ff758c] to-[#ff7eb3] text-white p-[1.1rem] border-none rounded-xl text-[1.1rem] font-bold cursor-pointer transition-all duration-300 mt-4 shadow-[0_4px_15px_rgba(255,154,158,0.4)] hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(255,154,158,0.6)] active:translate-y-0 disabled:opacity-70 disabled:cursor-not-allowed"
                        disabled={loading}
                    >
                        {loading ? '로그인 중...' : '로그인'}
                    </button>
                </form>

                <div className="text-center mt-10 text-[#666] text-[0.95rem] border-t border-[#f0f0f0] pt-6">
                    <p>아직 계정이 없으신가요? <Link to="/register" className="text-[#ff758c] font-semibold ml-1.5 hover:underline">회원가입</Link></p>
                </div>
            </div>
        </div>
    );
};

export default LoginView;
