// src/views/RegisterView.vue
<template>
  <div class="register-container">
    <h1 class="app-logo"><router-link to="/" class="logo">🎯 데이트코스</router-link></h1>
    <div class="register-box">
      <h2>회원가입</h2>
      
      <MessageAlert v-if="errorMessage" :message="errorMessage" type="error" />
      <MessageAlert v-if="successMessage" :message="successMessage" type="success" />

      <form @submit.prevent="handleRegister" class="register-form">
        <FormInput
          id="username"
          v-model="form.username"
          type="text"
          label="아이디"
          placeholder="아이디를 입력하세요"
          :error="usernameError"
          required
        />

        <FormInput
          id="email"
          v-model="form.email"
          type="email"
          label="이메일"
          placeholder="이메일을 입력하세요"
          :error="emailError"
          required
        />

        <FormInput
          id="password"
          v-model="form.password"
          type="password"
          label="비밀번호"
          placeholder="비밀번호를 입력하세요 (8자 이상)"
          :error="passwordError"
          required
          @blur="validatePassword"
        />

        <FormInput
          id="passwordConfirm"
          v-model="form.passwordConfirm"
          type="password"
          label="비밀번호 확인"
          placeholder="비밀번호를 다시 입력하세요"
          :error="passwordConfirmError"
          required
          @blur="validatePassword"
        />

        <FormInput
          id="nickname"
          v-model="form.nickname"
          type="text"
          label="닉네임"
          placeholder="닉네임을 입력하세요"
          required
        />

        <FormInput
          id="agree"
          v-model="form.agreeTerms"
          type="checkbox"
          label="이용약관 및 개인정보 수집에 동의합니다"
          required
        />

        <button type="submit" class="register-btn" :disabled="!isFormValid">회원가입</button>
      </form>

      <div class="register-footer">
        <p>이미 계정이 있으신가요? <router-link to="/login">로그인</router-link></p>
      </div>
    </div>
  </div>
</template>

<script>
import FormInput from '../components/FormInput.vue'
import MessageAlert from '../components/MessageAlert.vue'

export default {
  name: 'RegisterView',
  components: {
    FormInput,
    MessageAlert
  },
  data() {
    return {
      form: {
        username: '',
        email: '',
        password: '',
        passwordConfirm: '',
        nickname: '',
        agreeTerms: false
      },
      usernameError: '',
      emailError: '',
      passwordError: '',
      passwordConfirmError: '',
      errorMessage: '',
      successMessage: ''
    }
  },
  computed: {
    isFormValid() {
      return (
        this.form.username.length > 0 &&
        this.form.email.length > 0 &&
        this.form.password.length >= 8 &&
        this.form.password === this.form.passwordConfirm &&
        this.form.nickname.length > 0 &&
        this.form.agreeTerms &&
        !this.usernameError &&
        !this.emailError &&
        !this.passwordError &&
        !this.passwordConfirmError
      );
    }
  },
  methods: {
    validatePassword() {
      if (this.form.password.length < 8) {
        this.passwordError = '비밀번호는 8자 이상이어야 합니다.';
      } else {
        this.passwordError = '';
      }
      
      if (this.form.passwordConfirm && this.form.password !== this.form.passwordConfirm) {
        this.passwordConfirmError = '비밀번호가 일치하지 않습니다.';
      } else {
        this.passwordConfirmError = '';
      }
    },
    handleRegister() {
      if (!this.isFormValid) {
        this.errorMessage = '모든 필드를 올바르게 입력해주세요.';
        return;
      }

      // 비밀번호 확인
      if (this.form.password !== this.form.passwordConfirm) {
        this.passwordConfirmError = '비밀번호가 일치하지 않습니다.';
        return;
      }

      // TODO: 백엔드와 연동
      console.log('회원가입 시도:', {
        username: this.form.username,
        email: this.form.email,
        nickname: this.form.nickname
      });

      this.successMessage = '회원가입이 완료되었습니다! 로그인 페이지로 이동합니다.';
      this.errorMessage = '';
      
      setTimeout(() => {
        this.$router.push('/login');
      }, 2000);
    }
  },
  watch: {
    'form.password': function() {
      this.validatePassword();
    },
    'form.passwordConfirm': function() {
      this.validatePassword();
    }
  }
}
</script>

<style scoped>
.register-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 2rem;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  position: relative;
}

.app-logo {
  position: absolute;
  top: 2rem;
  left: 2rem;
  margin: 0;
}

.logo {
  color: white;
  text-decoration: none;
  font-size: 1.5rem;
  font-weight: bold;
  transition: opacity 0.3s ease;
}

.logo:hover {
  opacity: 0.8;
}

.register-box {
  background: white;
  border-radius: 10px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
  padding: 3rem;
  width: 100%;
  max-width: 450px;
}

.register-title {
  text-align: center;
  font-size: 2rem;
  margin-bottom: 0.5rem;
  color: #667eea;
}

.register-box h2 {
  text-align: center;
  font-size: 1.8rem;
  color: #333;
  margin-bottom: 2rem;
  font-weight: 600;
}

.register-form {
  display: flex;
  flex-direction: column;
  gap: 1.2rem;
}

.register-btn {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 1rem;
  border: none;
  border-radius: 5px;
  font-size: 1.1rem;
  font-weight: 600;
  cursor: pointer;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
  margin-top: 1rem;
}

.register-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
}

.register-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.register-btn:active:not(:disabled) {
  transform: translateY(0);
}

.register-footer {
  text-align: center;
  margin-top: 2rem;
  color: #666;
  font-size: 0.95rem;
}

.register-footer a {
  color: #667eea;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.3s ease;
}

.register-footer a:hover {
  color: #764ba2;
}

@media (max-width: 480px) {
  .register-box {
    padding: 2rem;
  }

  .register-box h2 {
    font-size: 1.5rem;
  }

  .register-form {
    gap: 1rem;
  }
}
</style>

// src/views/RegisterView.jsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import FormInput from '../components/FormInput';
import MessageAlert from '../components/MessageAlert';

const RegisterView = () => {
    const [form, setForm] = useState({
        username: '',
        email: '',
        password: '',
        passwordConfirm: '',
        nickname: '',
        agreeTerms: false
    });

    const [errors, setErrors] = useState({
        username: '',
        email: '',
        password: '',
        passwordConfirm: ''
    });

    const [statusMessage, setStatusMessage] = useState({
        message: '',
        type: '' // 'error' or 'success'
    });

    const navigate = useNavigate();

    const handleInputChange = (field, value) => {
        setForm(prev => ({
            ...prev,
            [field]: value
        }));
    };

    const validatePassword = () => {
        let passwordError = '';
        let passwordConfirmError = '';

        if (form.password.length > 0 && form.password.length < 8) {
            passwordError = '비밀번호는 8자 이상이어야 합니다.';
        }

        if (form.passwordConfirm.length > 0 && form.password !== form.passwordConfirm) {
            passwordConfirmError = '비밀번호가 일치하지 않습니다.';
        }

        setErrors(prev => ({
            ...prev,
            password: passwordError,
            passwordConfirm: passwordConfirmError
        }));
    };

    useEffect(() => {
        validatePassword();
    }, [form.password, form.passwordConfirm]);

    const isFormValid =
        form.username.length > 0 &&
        form.email.length > 0 &&
        form.password.length >= 8 &&
        form.password === form.passwordConfirm &&
        form.nickname.length > 0 &&
        form.agreeTerms &&
        !errors.password &&
        !errors.passwordConfirm;

    const handleRegister = (e) => {
        e.preventDefault();
        if (!isFormValid) {
            setStatusMessage({ message: '모든 필드를 올바르게 입력해주세요.', type: 'error' });
            return;
        }

        console.log('회원가입 시도:', {
            username: form.username,
            email: form.email,
            nickname: form.nickname
        });

        setStatusMessage({ message: '회원가입이 완료되었습니다! 로그인 페이지로 이동합니다.', type: 'success' });

        setTimeout(() => {
            navigate('/login');
        }, 2000);
    };

    return (
        <div className="min-h-screen flex justify-center items-center p-8 bg-[#fdfbfb] bg-[radial-gradient(circle_at_top_right,#fee_0%,transparent_40%),radial-gradient(circle_at_bottom_left,#eef_0%,transparent_40%)]">
            <h1 className="absolute top-8 left-8 m-0 z-10">
                <Link to="/" className="text-[1.8rem] font-extrabold bg-gradient-to-br from-[#ff758c] to-[#ff7eb3] bg-clip-text text-transparent">
                    🎯 데이트코스
                </Link>
            </h1>
            <div className="bg-white rounded-3xl shadow-lg p-12 w-full max-w-[480px] relative overflow-hidden border border-white/80 mt-8 before:content-[''] before:absolute before:top-0 before:left-0 before:w-full before:h-[6px] before:bg-gradient-to-br before:from-[#ff758c] before:to-[#ff7eb3] md:p-6">
                <h2 className="text-center text-[2rem] text-[#333] mb-10 font-extrabold">
                    회원가입
                </h2>

                {statusMessage.message && (
                    <MessageAlert
                        message={statusMessage.message}
                        type={statusMessage.type}
                        onDismiss={() => setStatusMessage({ message: '', type: '' })}
                    />
                )}

                <form onSubmit={handleRegister} className="flex flex-col gap-5">
                    <FormInput
                        id="username"
                        value={form.username}
                        onChange={(val) => handleInputChange('username', val)}
                        type="text"
                        label="아이디"
                        placeholder="아이디를 입력하세요"
                        required
                        error={errors.username}
                    />

                    <FormInput
                        id="email"
                        value={form.email}
                        onChange={(val) => handleInputChange('email', val)}
                        type="email"
                        label="이메일"
                        placeholder="이메일을 입력하세요"
                        required
                        error={errors.email}
                    />

                    <FormInput
                        id="password"
                        value={form.password}
                        onChange={(val) => handleInputChange('password', val)}
                        type="password"
                        label="비밀번호"
                        placeholder="비밀번호를 입력하세요 (8자 이상)"
                        required
                        error={errors.password}
                    />

                    <FormInput
                        id="passwordConfirm"
                        value={form.passwordConfirm}
                        onChange={(val) => handleInputChange('passwordConfirm', val)}
                        type="password"
                        label="비밀번호 확인"
                        placeholder="비밀번호를 다시 입력하세요"
                        required
                        error={errors.passwordConfirm}
                    />

                    <FormInput
                        id="nickname"
                        value={form.nickname}
                        onChange={(val) => handleInputChange('nickname', val)}
                        type="text"
                        label="닉네임"
                        placeholder="닉네임을 입력하세요"
                        required
                    />

                    <FormInput
                        id="agree"
                        value={form.agreeTerms}
                        onChange={(val) => handleInputChange('agreeTerms', val)}
                        type="checkbox"
                        label="이용약관 및 개인정보 수집에 동의합니다"
                        required
                    />

                    <button
                        type="submit"
                        className="bg-gradient-to-br from-[#ff758c] to-[#ff7eb3] text-white p-[1.1rem] border-none rounded-xl text-[1.1rem] font-bold cursor-pointer transition-all duration-300 mt-4 shadow-[0_4px_15px_rgba(255,154,158,0.4)] hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(255,154,158,0.6)] disabled:bg-[#ccc] disabled:cursor-not-allowed disabled:shadow-none hover:disabled:transform-none"
                        disabled={!isFormValid}
                    >
                        회원가입
                    </button>
                </form>

                <div className="text-center mt-10 text-[#666] text-[0.95rem] border-t border-[#f0f0f0] pt-6">
                    <p>이미 계정이 있으신가요? <Link to="/login" className="text-[#ff758c] font-semibold ml-1.5 hover:underline">로그인</Link></p>
                </div>
            </div>
        </div>
    );
};

export default RegisterView;
