// src/components/FormInput.vue
<template>
  <div class="form-group" :class="{ checkbox: type === 'checkbox' }">
    <input
      v-if="type !== 'checkbox'"
      :type="type"
      :id="id"
      :value="modelValue"
      :placeholder="placeholder"
      @input="$emit('update:modelValue', $event.target.value)"
      @blur="$emit('blur')"
      :required="required"
      :disabled="disabled"
    />
    <input
      v-else
      type="checkbox"
      :id="id"
      :checked="modelValue"
      @change="$emit('update:modelValue', $event.target.checked)"
      :required="required"
      :disabled="disabled"
    />
    <label v-if="label" :for="id">{{ label }}</label>
    <small v-if="error" class="error-text">{{ error }}</small>
  </div>
</template>

<script>
export default {
  name: 'FormInput',
  props: {
    modelValue: {
      type: [String, Boolean],
      required: true
    },
    type: {
      type: String,
      default: 'text'
    },
    id: {
      type: String,
      required: true
    },
    label: {
      type: String,
      default: ''
    },
    placeholder: {
      type: String,
      default: ''
    },
    error: {
      type: String,
      default: ''
    },
    required: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    }
  },
  emits: ['update:modelValue', 'blur']
}
</script>

<style scoped>
.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.form-group.checkbox {
  flex-direction: row;
  align-items: center;
  gap: 0.5rem;
}

.form-group.checkbox input {
  width: auto;
  cursor: pointer;
}

.form-group.checkbox label {
  margin-bottom: 0;
  cursor: pointer;
  flex: 1;
}

label {
  font-weight: 600;
  color: #333;
  font-size: 0.95rem;
}

input {
  padding: 0.7rem;
  border: 1px solid #ddd;
  border-radius: 5px;
  font-size: 0.95rem;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  transition: border-color 0.3s ease;
}

input:focus {
  outline: none;
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

input:disabled {
  background: #f5f5f5;
  cursor: not-allowed;
  opacity: 0.6;
}

.error-text {
  color: #cc3333;
  font-size: 0.85rem;
  margin-top: 0.3rem;
}
</style>

// src/components/FormInput.jsx
import React from 'react';

const FormInput = ({
    type = 'text',
    id,
    value,
    onChange,
    label,
    placeholder,
    error,
    required = false,
    disabled = false,
    onBlur
}) => {
    const isCheckbox = type === 'checkbox';

    return (
        <div className={`flex flex-col gap-2 relative mb-5 ${isCheckbox ? 'flex-row items-center gap-3 bg-[#f9f9f9] p-3 rounded-xl' : ''}`}>
            {/* Input Element */}
            {isCheckbox ? (
                <input
                    type="checkbox"
                    id={id}
                    checked={value}
                    onChange={(e) => onChange(e.target.checked)}
                    required={required}
                    disabled={disabled}
                    className="w-5 h-5 accent-[#ff758c] m-0"
                />
            ) : (
                <input
                    type={type}
                    id={id}
                    value={value}
                    placeholder={placeholder}
                    onChange={(e) => onChange(e.target.value)}
                    onBlur={onBlur}
                    required={required}
                    disabled={disabled}
                    className="p-3.5 px-4 border-2 border-[#eee] rounded-xl text-base font-inherit transition-all duration-300 bg-[#fdfdfd] focus:outline-none focus:border-[#ffb6b9] focus:shadow-[0_0_0_4px_rgba(255,154,158,0.1)] focus:bg-white placeholder:text-[#ccc]"
                />
            )}

            {/* Label */}
            {label && (
                <label
                    htmlFor={id}
                    className={`font-semibold text-[#333] text-sm ml-1 ${isCheckbox ? 'm-0 cursor-pointer flex-1 font-medium' : ''}`}
                >
                    {label}
                </label>
            )}

            {/* Error Message */}
            {error && (
                <small className="text-[#e74c3c] text-sm mt-1 flex items-center gap-1 before:content-['⚠️'] before:text-xs">
                    {error}
                </small>
            )}
        </div>
    );
};

export default FormInput;
