// src/components/MessageAlert.vue
<template>
  <div v-if="message" class="message-alert" :class="type">
    <span class="message-text">{{ message }}</span>
    <button v-if="dismissible" @click="$emit('dismiss')" class="close-btn">✕</button>
  </div>
</template>

<script>
export default {
  name: 'MessageAlert',
  props: {
    message: {
      type: String,
      default: ''
    },
    type: {
      type: String,
      enum: ['error', 'success', 'warning', 'info'],
      default: 'info'
    },
    dismissible: {
      type: Boolean,
      default: true
    }
  },
  emits: ['dismiss']
}
</script>

<style scoped>
.message-alert {
  padding: 1rem;
  border-radius: 5px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  font-weight: 500;
  animation: slideIn 0.3s ease;
}

@keyframes slideIn {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.message-alert.error {
  background: #fee;
  color: #c33;
  border-left: 4px solid #c33;
}

.message-alert.success {
  background: #efe;
  color: #3c3;
  border-left: 4px solid #3c3;
}

.message-alert.warning {
  background: #ffe;
  color: #cc6500;
  border-left: 4px solid #cc6500;
}

.message-alert.info {
  background: #eef;
  color: #33c;
  border-left: 4px solid #33c;
}

.message-text {
  flex: 1;
}

.close-btn {
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
  color: currentColor;
  opacity: 0.7;
  transition: opacity 0.3s ease;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-btn:hover {
  opacity: 1;
}
</style>

// src/components/MessageAlert.jsx
import React from 'react';

const MessageAlert = ({
    message,
    type = 'info',
    dismissible = true,
    onDismiss
}) => {
    if (!message) return null;

    const typeStyles = {
        error: "bg-[#fff5f5] text-[#c53030] border-[#fed7d7]",
        success: "bg-[#f0fff4] text-[#276749] border-[#c6f6d5]",
        warning: "bg-[#fffaf0] text-[#c05621] border-[#feebc8]",
        info: "bg-[#ebf8ff] text-[#2c5282] border-[#bee3f8]"
    };

    return (
        <div className={`p-4 px-6 rounded-xl flex justify-between items-center gap-4 font-medium animate-[slideIn_0.3s_cubic-bezier(0.25,0.8,0.25,1)] shadow-sm mb-6 border ${typeStyles[type] || typeStyles.info}`}>
            <span className="flex-1 text-[0.95rem]">{message}</span>
            {dismissible && (
                <button
                    onClick={onDismiss}
                    className="bg-transparent border-none text-lg cursor-pointer text-current opacity-60 p-1 rounded-full transition-all duration-200 flex items-center justify-center w-8 h-8 hover:opacity-100 hover:bg-black/5"
                >
                    ✕
                </button>
            )}
            <style jsx>{`
                @keyframes slideIn {
                    from { opacity: 0; transform: translateY(-20px); }
                    to { opacity: 1; transform: translateY(0); }
                }
            `}</style>
        </div>
    );
};

export default MessageAlert;
