// src/components/PlaceCard.jsx
import React from 'react';

const PlaceCard = ({ icon, name, category, distance, description, rating }) => {
    return (
        <div className="bg-white border border-black/5 rounded-2xl p-6 text-center transition-all duration-300 shadow-sm flex flex-col items-center h-full hover:-translate-y-2 hover:shadow-md hover:border-[#ffe0e0]">
            <div className="text-[3rem] mb-4 bg-[#fff0f5] w-20 h-20 rounded-full flex items-center justify-center">
                {icon}
            </div>
            <h3 className="text-[1.2rem] text-[#333] mb-2 font-bold">
                {name}
            </h3>
            <p className="text-[0.85rem] text-[#ff758c] font-semibold mb-1 uppercase tracking-wide">
                {category}
            </p>
            <p className="text-[0.9rem] text-[#999] mb-4 bg-[#f5f5f5] py-1 px-2.5 rounded">
                {distance}
            </p>
            <p className="text-[0.95rem] text-[#666] leading-relaxed mb-4 flex-grow">
                {description}
            </p>
            <div className="font-bold text-[#ffb400] text-[1.1rem]">
                ⭐ {rating}
            </div>
        </div>
    );
};

export default PlaceCard;

// src/components/PlaceCard.vue
<template>
  <div class="place-card">
    <div class="place-icon">{{ icon }}</div>
    <h3>{{ name }}</h3>
    <p class="place-category">{{ category }}</p>
    <p class="place-distance">{{ distance }}</p>
    <p class="place-description">{{ description }}</p>
    <div class="place-rating">⭐ {{ rating }}</div>
  </div>
</template>

<script>
export default {
  name: 'PlaceCard',
  props: {
    icon: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    category: {
      type: String,
      required: true
    },
    distance: {
      type: String,
      required: true
    },
    description: {
      type: String,
      required: true
    },
    rating: {
      type: String,
      required: true
    }
  }
}
</script>

<style scoped>
.place-card {
  background: white;
  border: 1px solid #eee;
  border-radius: 8px;
  padding: 1.5rem;
  text-align: center;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.place-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
}

.place-icon {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.place-card h3 {
  font-size: 1.1rem;
  color: #333;
  margin-bottom: 0.5rem;
  font-weight: 600;
}

.place-category {
  font-size: 0.85rem;
  color: #667eea;
  font-weight: 500;
  margin-bottom: 0.3rem;
}

.place-distance {
  font-size: 0.9rem;
  color: #666;
  margin-bottom: 0.5rem;
}

.place-description {
  font-size: 0.9rem;
  color: #666;
  line-height: 1.4;
  margin-bottom: 0.5rem;
}

.place-rating {
  font-weight: 600;
  color: #ff9800;
}
</style>
